package cli

import (
	"io"
	"net/url"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/IshaanNene/Tracepoint/internal/errs"
	"github.com/IshaanNene/Tracepoint/internal/ops"
)

// Environment names quick uses for values given on its command line, so the
// configuration references them and never contains them.
const (
	quickDSNEnv   = "TRACEPOINT_QUICK_DB_DSN"
	quickRedisEnv = "TRACEPOINT_QUICK_REDIS_ADDR"
)

func newQuickCmd(env Env, g *globals) *cobra.Command {
	var (
		opts                runOptions
		dsn, dsnEnv, driver string
		query               string
		redisAddr, redisEnv string
		rate                float64
		duration            time.Duration
		printConfig         bool
	)
	cmd := &cobra.Command{
		Use:   "quick <url>",
		Short: "A zero-configuration smoke test, probing the database and cache alongside",
		Long: strings.TrimSpace(`
Load one URL for a short while - 50 requests a second for 30 seconds unless told
otherwise - and, given a database DSN or a Redis address, probe those tiers on the same
clock so the result can say which one moved with the application.

A DSN given with --db-dsn reaches the run through the environment: the stored
configuration refers to $` + quickDSNEnv + ` rather than holding it, and its
password is redacted from every artifact, as for any DSN. Prefer --db-dsn-env NAME,
which references a variable you have set. The default probe query,
SELECT 1, cannot see the application's tables, and the digest says so; pass --db-query
with a read the application performs.

--print-config writes the equivalent configuration instead of running it, as a
starting point for a fuller test.`),
		Example: strings.TrimSpace(`
  tracepoint quick http://127.0.0.1:8080/api/items
  tracepoint quick http://127.0.0.1:8080/ --db-dsn-env DATABASE_URL --redis 127.0.0.1:6379
  tracepoint quick http://127.0.0.1:8080/ --db-dsn postgres://app@127.0.0.1/app --db-query "SELECT title FROM items WHERE id = 1"
  tracepoint quick http://127.0.0.1:8080/ --rate 100 --duration 1m --output json
  tracepoint quick http://127.0.0.1:8080/ --print-config > tracepoint.yaml`),
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			base, path, err := splitURL(args[0])
			if err != nil {
				return err
			}
			if dsn != "" && dsnEnv != "" {
				return errs.New(errs.CodeOpsInvalidInput, "--db-dsn and --db-dsn-env both name the database").WithHint("use one")
			}
			if redisAddr != "" && redisEnv != "" {
				return errs.New(errs.CodeOpsInvalidInput, "--redis and --redis-env both name the cache").WithHint("use one")
			}
			in := ops.ScaffoldIn{BaseURL: base, Paths: []string{path}, Rate: rate, Duration: duration.String(), DBQuery: query}
			extra := map[string]string{}
			if dsn != "" || dsnEnv != "" {
				in.DBDSNEnv = dsnEnv
				if dsn != "" {
					in.DBDSNEnv = quickDSNEnv
					extra[quickDSNEnv] = dsn
				}
				in.DBDriver = driver
				if in.DBDriver == "" {
					value := dsn
					if value == "" {
						value, _ = env.Lookup(dsnEnv)
					}
					if in.DBDriver = driverOf(value); in.DBDriver == "" {
						return errs.New(errs.CodeOpsInvalidInput, "cannot tell the database driver from the DSN").
							WithHint("pass --db-driver postgres, mysql or sqlite")
					}
				}
			}
			if redisAddr != "" || redisEnv != "" {
				in.RedisAddrEnv = redisEnv
				if redisAddr != "" {
					in.RedisAddrEnv = quickRedisEnv
					extra[quickRedisEnv] = redisAddr
				}
			}
			yaml, _, err := ops.Scaffold(in)
			if err != nil {
				return err
			}
			if printConfig {
				header := "# Generated by `tracepoint quick`.\n"
				if dsn != "" {
					header += "# The DSN given on the command line is not written here: set " + quickDSNEnv + ", or edit db.dsn.\n"
				}
				if redisAddr != "" {
					header += "# Set " + quickRedisEnv + " to the Redis address, or edit redis.addr.\n"
				}
				_, err := io.WriteString(env.Stdout, header+yaml)
				return err
			}
			opts.source, opts.sourceLabel, opts.extraEnv = []byte(yaml), "quick", extra
			return runRun(cmd.Context(), env, g, opts)
		},
	}
	f := cmd.Flags()
	f.StringVar(&dsn, "db-dsn", "", "probe this database; the stored configuration references it through the environment, and its password is redacted everywhere")
	f.StringVar(&dsnEnv, "db-dsn-env", "", "probe the database whose DSN is in this environment variable")
	f.StringVar(&driver, "db-driver", "", "postgres, mysql or sqlite; inferred from the DSN when it can be")
	f.StringVar(&query, "db-query", "", "the database probe's query (default SELECT 1, which sees none of the application's tables)")
	f.StringVar(&redisAddr, "redis", "", "probe the Redis at this address")
	f.StringVar(&redisEnv, "redis-env", "", "probe the Redis whose address is in this environment variable")
	f.Float64Var(&rate, "rate", 50, "requests per second to the URL")
	f.DurationVar(&duration, "duration", 30*time.Second, "how long to run")
	f.BoolVar(&printConfig, "print-config", false, "write the equivalent configuration instead of running it")
	f.StringVar(&opts.policyPath, "policy", "", "safety policy file; defaults to $TRACEPOINT_POLICY, then to an envelope that refuses public targets and grants no writes")
	f.StringVar(&opts.runRoot, "run-root", "", "directory run directories are created under")
	f.StringVar(&opts.events, "events", "", "stream events as NDJSON: - for stdout, or a file path")
	f.StringVar(&opts.resultPath, "result-path", "", "also write result.json here")
	f.StringVar(&opts.reportPath, "report-path", "", "also write report.html here")
	f.BoolVar(&opts.noLive, "no-live", false, "log a progress line every 5s instead of drawing the live view")
	f.BoolVar(&opts.allowInvalid, "allow-invalid", false, "exit 0 for a run the generator bottlenecked, instead of 4")
	f.BoolVarP(&opts.verbose, "verbose", "v", false, "include the per-label table")
	return cmd
}

// splitURL separates a URL into the base the configuration holds and the path it
// loads.
func splitURL(raw string) (base, path string, err error) {
	u, err := url.Parse(raw)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
		return "", "", errs.New(errs.CodeOpsInvalidInput, "%q is not an http or https URL", raw).
			WithHint("for example http://127.0.0.1:8080/api/items")
	}
	path = u.EscapedPath()
	if path == "" {
		path = "/"
	}
	if u.RawQuery != "" {
		path += "?" + u.RawQuery
	}
	return u.Scheme + "://" + u.Host, path, nil
}

// driverOf infers a database driver from a DSN's form.
func driverOf(dsn string) string {
	lower := strings.ToLower(dsn)
	switch {
	case strings.HasPrefix(lower, "postgres://"), strings.HasPrefix(lower, "postgresql://"),
		strings.Contains(lower, "host=") && strings.Contains(lower, "dbname="):
		return "postgres"
	case strings.HasPrefix(lower, "mysql://"), strings.Contains(lower, "@tcp("), strings.Contains(lower, "@unix("):
		return "mysql"
	case strings.HasPrefix(lower, "file:"), strings.HasSuffix(lower, ".db"), strings.HasSuffix(lower, ".sqlite"),
		strings.HasSuffix(lower, ".sqlite3"), lower == ":memory:":
		return "sqlite"
	}
	return ""
}
